name: rag-qlora-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - intel-openmp=2023.1.0=ha357a0b_43548
  - libcxx=20.1.5=hf95d169_0
  - libffi=3.4.4=hecd8cb5_1
  - mkl=2023.1.0=h8e150cf_43560
  - ncurses=6.4=hcec6c5f_0
  - openssl=3.5.0=hc426f3f_1
  - pip=25.1=pyhc872135_2
  - python=3.10.16=hce00570_1
  - readline=8.2=hca72f7f_0
  - setuptools=78.1.1=py310hecd8cb5_0
  - sqlite=3.45.3=h6c40b1e_0
  - tbb=2021.8.0=ha357a0b_0
  - tk=8.6.14=h4d00af3_0
  - wheel=0.45.1=py310hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - accelerate==1.7.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.2
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==4.0.3
      - attrs==25.3.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.4
      - bitsandbytes==0.42.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cryptography==45.0.3
      - dataclasses-json==0.6.7
      - datasets==3.6.0
      - dill==0.3.8
      - diskcache==5.6.3
      - emoji==2.14.1
      - exceptiongroup==1.3.0
      - faiss-cpu==1.8.0
      - fastapi==0.115.13
      - filelock==3.18.0
      - filetype==1.2.0
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - greenlet==3.2.2
      - h11==0.16.0
      - hf-xet==1.1.2
      - html5lib==1.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.32.1
      - idna==3.10
      - iniconfig==2.1.0
      - inquirerpy==0.3.4
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.4
      - langchain-community==0.3.3
      - langchain-core==0.3.12
      - langchain-huggingface==0.1.0
      - langchain-text-splitters==0.3.0
      - langdetect==1.0.9
      - langsmith==0.1.147
      - llama-cpp-python==0.3.9
      - lxml==5.4.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==1.26.4
      - olefile==0.47
      - ollama==0.5.1
      - orjson==3.10.18
      - packaging==24.1
      - pandas==2.2.3
      - peft==0.15.2
      - pfzy==0.3.4
      - pillow==11.2.1
      - pluggy==1.6.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pycparser==2.22
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - pymupdf==1.26.0
      - pypdf==5.5.0
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-iso639==2025.2.18
      - python-magic==0.4.27
      - python-oxmsg==0.0.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - rapidfuzz==3.13.0
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - sentence-transformers==3.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - sqlalchemy==2.0.41
      - starlette==0.46.2
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==2.2.2
      - tqdm==4.67.1
      - transformers==4.45.2
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - unstructured==0.17.2
      - unstructured-client==0.35.0
      - urllib3==2.4.0
      - uvicorn==0.34.3
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.20.0
      - zstandard==0.23.0
prefix: /opt/anaconda3/envs/rag-qlora-bot
